# 1)Create an array with Numpy


In [3]:
import numpy as np
from numpy import dtype
from numpy.ma.extras import hsplit

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [7]:
np.array([3.13,5,4,121])

array([  3.13,   5.  ,   4.  , 121.  ])

#### 1. Dtype kullanarak ozel bir tip olsuturabiliyoruz

In [ ]:
np.array([3.13,4,1,23], dtype="float32")

#### 2.Sifirdan array olusturma


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10, dtype="int32")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### 3.Birlerden array olusturma


In [10]:
np.ones([3,5], dtype=int) # 3 satir 5 sutunluk 2 boyutlu array olrusutma

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 4. Istedigimiz sayilardan array olsuturma

In [11]:
np.full([2,3],3,dtype=int)

array([[3, 3, 3],
       [3, 3, 3]])

#### 5. Dogrusal bir array olsuturma

In [12]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

#### 6. Istedigimiz sayi arasinda belirli miktarda aritmetik deger olsutruma

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 7. Ortalama standrat sapma vererek normal dagilim

In [14]:
np.random.normal(10,4,(3,2))

array([[ 9.41342549,  4.23481375],
       [ 3.57916384,  9.3851152 ],
       [16.10589133, 12.92037621]])

#### # tek boyutlu arrayin karsiligi vektor 2 boyutlu arrayin karsiligi matris

#### 8. dagilimsiz int deger olsuturma


In [16]:
np.random.randint(0,10,(3,2))


array([[1, 1],
       [0, 5],
       [4, 2]])

#### Sıklıkla kullanacagımız **randınt** **normal** **arange**

# 2) Array Ozellikleri
* **ndim** : boyut sayisi
* **shape** : boyut bilgisi
* **size** : toplam eleman sayisi
* **dtype** : array veri tipi

In [17]:
np.random.randint(10, size=10)

array([6, 0, 4, 0, 7, 6, 3, 6, 6, 3])

In [18]:
a = np.random.randint(10, size=10)


#### ndim = boyut sayisi

In [19]:
a.ndim

1

#### shape boyut bilgisi

In [20]:
a.shape # 1 boyutlu oldugundan o boyutta 10 tane eleman var deniliyor

(10,)

#### Size eleman sayisi

In [21]:
a.size # 10 elemanli

10

#### dtype array veri tipini verir

In [23]:
a.dtype

dtype('int64')

#### 2 boyutlu array larda fonksiyonlari kullanmak

In [28]:
b = np.random.randint(10, size=(3,5))

In [29]:
b.ndim


2

In [31]:
b.shape

(3, 5)

In [30]:
b.size

15

In [32]:
b.dtype

dtype('int64')

# 4) Reshape (Yeniden Sekillendirme)
* olsutrudgumuz arrayi farkli boyutlara donusturmek icin kullaniriz

In [40]:
a = np.arange(1,10)

In [41]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a.ndim

1

In [43]:
b = a.reshape((1,9))

In [44]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
b.ndim

2

# 5) Concatenation (Array Birlestirme)

### Tek boyut uzerine array birlestirme

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [51]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

yeni bir array olsuturup onu da ekleyebilir miyim

In [53]:
z = np.array([7,8,9])

In [54]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### iki boyutlu arraylarda birlestirme

In [55]:
a = np.array([[1,2,3],
              [4,5,6]])

#### iki boyutlu array birlestirme

In [56]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

#### iki boyutlu arrayi axis e gore birlestirme
* axis = 0

In [57]:
np.concatenate([a,a],axis=0) # axis = 0 satira gore birlestirir auto degeri 0 dir

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* axis = 1
* axis = 1 i sutuna bolerek birlestirme islemi yapti

In [58]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# 6) Splitting (Array Ayirma)

### Bir bouytlu arraylarda bolme

In [59]:
x = np.array([1,2,3,99,99,3,2,1])

In [60]:
np.split(x,[3,5]) # 0 dan 3 e kadar 3 ten 5 e kadar gerisini de oylece koy

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

bu degerleri variable a atamak icin ne yapiyoruz

In [61]:
a,b,c = np.split(x, [3,5])

In [62]:
a

array([1, 2, 3])

In [63]:
b

array([99, 99])

In [64]:
c

array([3, 2, 1])

### Iki boyutlu arraylarda bolme islemi

In [67]:
m = np.arange(16).reshape((4,4))

In [68]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Normal Bolme


In [71]:
np.split(m,[2]) # 2 ye kadar bolme

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

* Horizontal Bolme

In [72]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [75]:
sol,sag = np.hsplit(m,2)

In [76]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [77]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

* Vertical Bolme

In [78]:
np.vsplit(m,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [79]:
ust,alt = np.vsplit(m,2)

In [80]:
ust


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
alt


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# 7) Sort (Siralama)

### Tek boyutlu arraylarda siralama

In [82]:
a = np.array([1,4,6,4,2,3,5])
a

array([1, 4, 6, 4, 2, 3, 5])

* arrayin ilk halini degistirmeyen siralama

In [83]:
np.sort(a)

array([1, 2, 3, 4, 4, 5, 6])

In [84]:
a

array([1, 4, 6, 4, 2, 3, 5])

* arrayin ilk halini degistiren siralama

In [85]:
a.sort()

In [86]:
a

array([1, 2, 3, 4, 4, 5, 6])

### 2 boyutlu arraylarda siralama islemi

In [87]:
m = np.random.normal(20,5,(3,5))

In [88]:
m

array([[22.48850095, 17.19004222, 13.56555323, 21.45679735, 17.47559851],
       [20.95356911, 27.63418784, 25.15337409, 22.8107977 , 26.62432139],
       [18.78960263, 18.77436426, 28.33934443, 25.44121318, 11.80584486]])

* satira gore siralama
* axis = 1 stunlari siralar

In [90]:
np.sort(m,axis=1)

array([[13.56555323, 17.19004222, 17.47559851, 21.45679735, 22.48850095],
       [20.95356911, 22.8107977 , 25.15337409, 26.62432139, 27.63418784],
       [11.80584486, 18.77436426, 18.78960263, 25.44121318, 28.33934443]])

* satiri  siralama (yukaridan asagiya)
* axis = 0

In [91]:
np.sort(m,axis=0)

array([[18.78960263, 17.19004222, 13.56555323, 21.45679735, 11.80584486],
       [20.95356911, 18.77436426, 25.15337409, 22.8107977 , 17.47559851],
       [22.48850095, 27.63418784, 28.33934443, 25.44121318, 26.62432139]])

* default siralama
* satira gore siralar
* yani axis = 1

In [92]:
np.sort(m)

array([[13.56555323, 17.19004222, 17.47559851, 21.45679735, 22.48850095],
       [20.95356911, 22.8107977 , 25.15337409, 26.62432139, 27.63418784],
       [11.80584486, 18.77436426, 18.78960263, 25.44121318, 28.33934443]])

# 8) Index ile elemanlara erisme


In [94]:
a = np.random.randint(1,10,10)
a

array([8, 1, 3, 2, 3, 9, 3, 7, 9, 7])

In [95]:
a[0]

np.int64(8)

In [96]:
a[-1]

np.int64(7)

In [97]:
a[0] = 100
a

array([100,   1,   3,   2,   3,   9,   3,   7,   9,   7])

In [98]:
m = np.random.randint(10, size=(3,5))
m

array([[7, 1, 9, 0, 7],
       [3, 6, 9, 5, 1],
       [2, 7, 1, 0, 6]])

In [99]:
m[0:2,1:3]

array([[1, 9],
       [6, 9]])

In [100]:
m[0,2]

np.int64(9)

In [101]:
m[1,0]

np.int64(3)

In [102]:
m[1,3] = 100
m

array([[  7,   1,   9,   0,   7],
       [  3,   6,   9, 100,   1],
       [  2,   7,   1,   0,   6]])

# 9) Slicing (Alt Kume Islemleri)

### tek boyutta islemler

In [103]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
a[0:3]

array([20, 21, 22])

* [n::a] n. ci elemandan a kadar artarak goster


In [106]:
a[0::2]

array([20, 22, 24, 26, 28])

### iki boyutlu islemler

In [108]:
m = np.random.randint(20, size=(6,6))
m

array([[12,  6, 14,  6,  7,  2],
       [ 3,  0,  7, 17, 19,  2],
       [ 2, 17, 14, 14, 17,  2],
       [ 8,  2, 17, 15,  3, 12],
       [10, 18,  0,  8, 12, 10],
       [16,  8,  6,  9, 11,  9]])

In [110]:
m[0:2,2:]

array([[14,  6,  7,  2],
       [ 7, 17, 19,  2]])

In [112]:
m[:,3] # 3. sutun

array([ 6, 17, 14, 15,  8,  9])

In [113]:
m[0] # ilk satiri direkt getiriyor

array([12,  6, 14,  6,  7,  2])

In [115]:
m

array([[12,  6, 14,  6,  7,  2],
       [ 3,  0,  7, 17, 19,  2],
       [ 2, 17, 14, 14, 17,  2],
       [ 8,  2, 17, 15,  3, 12],
       [10, 18,  0,  8, 12, 10],
       [16,  8,  6,  9, 11,  9]])

In [116]:
m[::,:2] # tum satirlari al 2 ye kadar olan satirlari al

array([[12,  6],
       [ 3,  0],
       [ 2, 17],
       [ 8,  2],
       [10, 18],
       [16,  8]])

# 10) Alt Kume uzerinde islem yapmak
* alt kumelerde islemk yaparken kumenin kendisi de degisiklige ugrayabiliyor
* biz bazen sadece degisiklik alt kumelerde olmasini isteriz

In [117]:
a = np.random.randint(10, size=(5,5))
a

array([[1, 5, 0, 1, 1],
       [6, 2, 6, 5, 8],
       [6, 4, 3, 4, 8],
       [8, 3, 1, 2, 3],
       [1, 9, 3, 2, 3]])

In [118]:
sub_a = a[0:3,0:2]

In [119]:
sub_a

array([[1, 5],
       [6, 2],
       [6, 4]])

In [124]:
sub_a[0,0] = 9999
sub_a[1,1] = 888
sub_a

array([[9999,    5],
       [   6,  888],
       [   6,    4]])

In [123]:
a

array([[9999,    5,    0,    1,    1],
       [   6,  888,    6,    5,    8],
       [   6,    4,    3,    4,    8],
       [   8,    3,    1,    2,    3],
       [   1,    9,    3,    2,    3]])

* gorulecegi uzere a da da degiskenler degisti

#### SADECE SUB Item daki islemleri degistirme

* copy() methodunu kullanacagiz

In [125]:
m = np.random.randint(10, size=(5,5))
m

array([[2, 0, 1, 0, 6],
       [5, 2, 8, 6, 6],
       [1, 3, 5, 4, 4],
       [8, 0, 0, 5, 3],
       [6, 7, 7, 0, 2]])

In [127]:
sub_m = m[0:3,0:2].copy()
sub_m

array([[2, 0],
       [5, 2],
       [1, 3]])

In [129]:
sub_m[0,0] = 999
sub_m[1,1] = 888
sub_m

array([[999,   0],
       [  5, 888],
       [  1,   3]])

In [130]:
m

array([[2, 0, 1, 0, 6],
       [5, 2, 8, 6, 6],
       [1, 3, 5, 4, 4],
       [8, 0, 0, 5, 3],
       [6, 7, 7, 0, 2]])

* gorulecegi uzere m de hic bir degisiklik olmadi

# 11) Fancy Index ile ELemanlara erismek
* cok onemli bir kavram
* daha ileri duzeyde eleaman secme islemlerini yapar
* tek tek verileri secmek yerine tek bir islem ile sectigimiz verielri getirebiliriz

### TEK BOYUTTA FANCY

In [131]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

1 3 5 inci indexleri getirme


In [133]:
a[1]

np.int64(3)

In [134]:
a[3]

np.int64(9)

In [135]:
a[5]

np.int64(15)

bunlari array seklinde de alabiliriz

In [136]:
[a[1],a[3],a[5]]

[np.int64(3), np.int64(9), np.int64(15)]

fakat yuzlerce veri de bunlari tek tek secmektense daha mantikli bir islem var
#### fancy mantigi

In [137]:
indexs = [1,3,5]

In [138]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

**bu sekilde yaparsak direkt array halinde istedigimiz indexi getirir**

In [139]:
a[indexs]

array([ 3,  9, 15])

### IKI BOYUTTA FANCY

* iki boyutlu array olsutur
* satir ve sutunlari belirle
* [satir,sutun] seklinde yaz

In [140]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [143]:
satir = np.array([1,2])
sutun = np.array([1,1])
m[satir,sutun]

array([4, 7])

* basit index ile fancy

In [144]:
m[1,[1,2]]

array([4, 5])

* slicing ile fancy

In [146]:
m[0:2, [1,2]]

array([[1, 2],
       [4, 5]])

# 12) Boolean Indexing (Kosullu Eleman Islemleri)

In [147]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

* array degeri buyuk mu / true-false

In [148]:
v > 5

array([False, False, False, False, False])

In [149]:
v < 3

array([ True,  True, False, False, False])

## fancy ile kosulu karsilayan sonuclari alma
* true olan sonuclari getirir
*

In [150]:
v[v < 3]

array([1, 2])

In [151]:
v[v<=3]

array([1, 2, 3])

In [152]:
v[v==3]

array([3])

In [153]:
v[v>=3]

array([3, 4, 5])

In [154]:
v[v!=3]

array([1, 2, 4, 5])

In [155]:
v

array([1, 2, 3, 4, 5])

### skaler carpim

In [156]:
v * 2

array([ 2,  4,  6,  8, 10])

In [158]:
v/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [159]:
v/5*10

array([ 2.,  4.,  6.,  8., 10.])

In [160]:
v ** 2

array([ 1,  4,  9, 16, 25])

# 13) Matematiksel Islemler

In [161]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

* her ne kadar matematiksel operatorleri kullansakta **ufunc** denilen islem devreye giriyor arka planda

cikarma


In [162]:
v -1

array([0, 1, 2, 3, 4])

toplama

In [165]:
v + 5

array([ 6,  7,  8,  9, 10])

carpma

In [163]:
v * 5

array([ 5, 10, 15, 20, 25])

bolme

In [166]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

karesi gibi ifadeleri alma


In [164]:
v ** 3

array([  1,   8,  27,  64, 125])

kalanlari alma

In [176]:
v % 2

array([1, 0, 1, 0, 1])

### **ufunc** ile alma
* cikarma

In [168]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

* toplama

In [170]:
np.add(v,5)

array([ 6,  7,  8,  9, 10])

* carpma

In [171]:
np.multiply(v,5)

array([ 5, 10, 15, 20, 25])

* bolme

In [172]:
np.divide(v,6)

array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])

* square alma

In [175]:
np.power(v,2)

array([ 1,  4,  9, 16, 25])

* kalanlari bulma

In [177]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

* mutlak degerini alma
* -degeri artiya cevriri

In [178]:
np.absolute(np.array([-2]))

array([2])

### Sinus cosinus tan cot hesaplama

In [180]:
np.sin(360)

np.float64(0.9589157234143065)

In [181]:
np.cos(180)

np.float64(-0.5984600690578581)

In [182]:
np.tan(90)

np.float64(-1.995200412208242)

### Log alma

In [183]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [184]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229])

* log tabani degistirebiliiriz
*

In [185]:
np.log2(arr)

array([0.       , 1.       , 1.5849625])

In [186]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125])

### Statistic


In [ ]:
# MEAN
# np.mean(arr, axis=0)
# Returns mean of arr along specified axis
# SUM
# arr.sum()
# Returns the sum of elements in arr
# MIN
# arr.min()
# Returns minimum value of arr
# MAX
# arr.max(axis=0)
# Returns maximum value of arr along specified axis
# VAR
# np.var(arr)
# Returns the variance of arr
# STD
# np.std(arr, axis=1)
# Returns the standard deviation of arr along specified axis
# CORRCOEF
# arr.corrcoef()
# Returns correlation coefficient of arr

# 14) Numpy ile iki bilinmeyenli denklem cozumu

* ### lineer cebir alanina gore gelistirilen **linalg**

5 * x0 + x1 = 12

x0 + 3* x1 = 10

iki bilinmeyenli bir denklemi bulabilmek icin yaptigimiz islem
* ilk basta bilinmeyenlerin kat sayilarini bir arraya aliriz ayri ayri
* sonucu farkli bir arraya aliriz
* sonrasinda linalg fonk solve methodunu kullaniriz

In [189]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [192]:
solve = np.linalg.solve(a,b)
solve


array([1.85714286, 2.71428571])